# Generated by Django 3.1.2 on 2022-07-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20220727_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='links',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
